# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 824e58cbdee5710c8561cd2249c8f442384b262d7836fbc59345ba71f9fae8db4160e5025596950b23cfad0ace3372d5d09476d45de965f0e19710a29762cae4

test:
  secret_key_base: b0fd03931fd17637b918609e0ce199e4aa38ac8a5559bbdd0d2b55938cdb820d601ffa1a33b1c87aeac46050140a136c73c3aedf68bf147ff509d2ec48526af8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
